### ISSUE TITLE
file greater than 16k

### ISSUE THREAD

**Issue by ra1nb0w** [StormTrooper/eeprom_programmer#1]
Hi,
first of all thank you for sharing this project!
I am trying to write a full 27C256 (32768 bytes) but I stuck with the error. I suppose that limit it is an hard limit from 328P.
Therefore the only way to circumvent this is to stream the data from the PC or use a bigger AVR chip. Right?
Another question: can the W27C512 replace the 27C256 without any changes in the destination hardware?

have a great Sunday

**Comment by StormTrooper** [comment]
You will need to break the file up in to 16k chunks and then write the first 16k to 0x0000h and then the next 16k to 0x8000h

You can use the W27c512 without any changes to the hardware.

**Comment by ra1nb0w** [comment]
you are right! Is there any issue for an eprom to write addresses in two slices? I mean, the write once is per cell? thank you

**Comment by StormTrooper** [comment]
You should be able to program the lower bank and then upper bank without any issues. You can't write to the same memory address twice.

**Comment by ra1nb0w** [comment]
I made a PCB. I will try and I hope to do so. thank you

**Comment by ra1nb0w** [comment]
Just as fix: 16K start from 0x4000h not 0x8000h.
Since I have only one chip I want to be sure that the procedure is correct:
- splited the 32k original hex and checked that the concatenation is the same (hash check)
- generate the first part bin_file.h
- flash the arduino nano
- connecto to the serial at 115200
- select "Write" "27C256" "0000" and wait (I can also verify then)
- generate the second part bin_file.h and flash the arduino 
- connect to the serial at 115200
- select "Write" "27C256" "4000" and wait (I can also verify then)

Correct? Do I need to check something before start writing? 12V line ecc?

**Update:** the procedure works flawless. thank you for sharing the code!

**Comment by ra1nb0w** [comment]
Note:
Q3, Q4 and Q4 have collector/emiter inverted. If you use 2N3906 everything is correct.
